### ISSUE TITLE
Can I get changes from LDAP server?

### ISSUE THREAD

**Issue by PrasadChinthala** [FreeDSx/LDAP#11]
Can I get changes from LDAP server if any CRUD operations done on LDAP server like in "Azure Active Directory(AAD)", if I use GetChanges.php file (https://github.com/Azure-Samples/active-directory-php-graphapi-web) then I will get all the changes done on AAD.  I have searched all the files & folder before asking this question.

**Comment by ChadSikorra** [comment]
Based on my understanding of that operation for Graph API, it is used as such:

* Perform an initial query operation to track changes for a set of objects
* Perform subsequent queries using some sort of session state / id / cookie from the original query to get the changes that occurred since that initial query.

So is it your intention to be able to track changes from a specific point after a query? This doesn't seem to be able to list all changes unless you specifically request to track them with a starting query.

The closest thing I can find to do that with Active Directory would be the `LDAP_SERVER_DIRSYNC_OID` control, which is documented here:

https://msdn.microsoft.com/en-us/library/cc223347.aspx

I have never used that control before. Though it should work to create a new class extending the base control in this library to create it.

**Comment by ChadSikorra** [comment]
At the very least I can create new control classes called DirSyncRequest / DirSyncResponse and make it easier to use based off the MS docs, and provide some examples for it. Not sure when specifically I will get around to it. Though I still need to tag a new release after moving the TCP stuff to its own library.

**Comment by ChadSikorra** [comment]
It may not be possible to implement this currently for this library. Pending a response here:

https://social.msdn.microsoft.com/Forums/en-US/163e2656-7d0b-4735-8d75-1f90b7ea4869/msadts-3113413-ldapserverdirsyncoid-authtype-requirement-question?forum=os_specifications

I may need to first implement additional authentication types before the control even works as expected.

**Comment by ChadSikorra** [comment]
Well that was interesting. Apparently one of the flags is not encoded how you would expect in that control. Worked around that to get a working control. Added the control in commit https://github.com/FreeDSx/LDAP/commit/006e9bb5d9e28918689979f859a8d8e2a809222b. I plan to add a helper class similar to the paging helper.

**Comment by ChadSikorra** [comment]
I have added a DirSync helper class to the client: https://github.com/FreeDSx/LDAP/commit/c9d39eff847997cc6bba9a058de98738b3bfa312. You can now monitor changes to AD using two different methods, depending on your preference.

Method # 1. Expect the initial results search to take a while depending on the size of your AD..:

```php
# Store initial results of the sync here. This is just all entries matching the LDAP filter.
# The default filter is: (objectClass=*)
$initialResults = null;
# Get the the DirSync helper from the LdapClient class.
$dirSync = $ldap->dirSync();

while (true) {
    $all = $dirSync->getChanges();
    while ($dirSync->hasChanges()) {
        $all->add(...$dirSync->getChanges());
    }
    if ($initialResults === null) {
        $initialResults = $all;
        var_dump('Initial sync: '.count($all));
    } else {
        var_dump('Changes: '.count($all));
    }
    sleep(10);
}
```

Method # 2, use the `watch()` method with an anonymous function (polls for changes every 10 seconds by default):

```php
use FreeDSx\Ldap\Entry\Entries;

$ldap->dirSync()->watch(function (Entries $entries, bool $isFirstSync) {
    if ($isFirstSync) {
        var_dump('Initial sync: '.count($entries));
    } else {
        var_dump('Changes: '.count($entries));
        foreach ($entries as $entry) {
            var_dump($entry->toArray());
        }
    }
});
```

I will add a separate doc on the full abilities of the helper class later.

**Comment by ChadSikorra** [comment]
Full documentation added here:

https://github.com/FreeDSx/LDAP/blob/master/docs/Client/DirSync.md

Will be tagging a new release within the next month or two. Marking as closed. If you have any questions, let me know.
