### ISSUE TITLE
Search missing attribute

### ISSUE THREAD

**Issue by podhy** [FreeDSx/LDAP#2]
Hello,
when I do LDAP search for missing attribute, library got stuck. Example:
```php
$search = Operations::search(Filters:: and (
    Filters::equal('objectClass', 'user'),
    Filters::equal('sAMAccountName', 'some.existing.user')
), new Attribute('missingAttribute'));

$ldapResult = $this->ldap->search($search); // got stuck
```

Without attributes its ok.

**Comment by ChadSikorra** [comment]
Thanks for reporting that. Pretty interesting to track down the cause of it. Turned out to be a small mistake in my indefinite length checks in the BER encoder for partial PDU detection. Should be fixed with https://github.com/FreeDSx/LDAP/commit/579800054125808a9861ffda7f1046758e9cf261. Let me know if that fixes it for you.

**Comment by podhy** [comment]
Nice. It works. Thx.
