### ISSUE TITLE
Using the library in production.

### ISSUE THREAD

**Issue by nexvelius** [FreeDSx/LDAP#20]
Hello @ChadSikorra!

Probably, someone already asked a similar question earlier, but my question actually much more, than simply work in production.

First of all, I would like to say that you have an amazing job! I've never used your library before, but I'm delighted with the amount of work you've done exploring your code.

I have an idea, in the context of the application I'm working on. Not to be verbose, we interact with LDAP in the context of users and groups and this imposes some restrictions. The idea is to implement the possibility of "synchronizing" users and groups into our repository (for example on PostgreSQL), I understand that this approach has certain drawbacks, but there are also certain advantages. (I can tell you about it in more detail, if you want)

Ultimately, this can turn into a "multi-store" where we can connect a large number of different services, whether LDAP or something else.

To solve this problem, I considered Golang and the [go-ldap](https://github.com/go-ldap/ldap) library, but its author has almost ceased to deal with it, and I, unfortunately, do not know golang and ldap well enough to accompany her.

For me it was a surprise to find your library in php and I think that I could contribute to its development if I decide to work with it.

I have a few questions.:
 1. Do you use your library in production?
 2. Have you tested your library on Windows?
 3. Have you tested your library with things like: 
[roadrunner](https://github.com/spiral/roadrunner), [reactphp](https://reactphp.org/), [amp](https://amphp.org)
 4. Whether you are on active development?

 I will be very grateful for your answers, thank you!

**Comment by ChadSikorra** [comment]
Hi there @nexvelius . Thanks for the feedback! To answer some of the questions:

1. **Do you use your library in production?**

Not in a "corporate" production environment perspective. My current day job is as a Systems Administrator, so I don't get to use my PHP projects for any automation efforts there. But this library has a pretty extensive suite of specs and and tests that run against both OpenLDAP and Active Directory using large amounts of sample data. These tests are run via CI on both Windows and Linux. 

I would consider this library "production" ready in its current state. Though if people encounter issues I would love the feedback to help improve the library overall.
 
2. **Have you tested your library on Windows?**

Yes, all of the specs and tests run against both Windows and Linux. I did a large amount of the development of this library on a Windows 10 machine actually. When I did performance tweaking I tested using this library from both Windows and Linux machines.

The only part of this library that doesn't function the same on Windows as it does on Linux is the LDAP server component. That has more to do with the limitations of threads and forking in PHP on Windows than anything else.

3. **Have you tested your library with things like: roadrunner, reactphp, amp**

No, but only because I haven't used any of those yet. If any issues are found using this library with those I would be glad to help fix them.

4. **Whether you are on active development?**

Real life time permitting, yes. As I develop all of these libraries in my free time as a hobby. But I plan to actively maintain the various `freedsx/*` libraries. I'm actively working on 2 separate features at the moment. SASL support and LDAP Synchronization support (OpenLDAP syncrepl basically).

**Comment by nexvelius** [comment]
>  I'm actively working on 2 separate features at the moment. SASL support and LDAP Synchronization support (OpenLDAP syncrepl basically).

That's great! I look forward to your results in this direction. (This is very important in my task)

Thank you for your very detailed answer.
