### ISSUE TITLE
Problem with German umlauts

### ISSUE THREAD

**Issue by Stephanowicz** [FreeDSx/LDAP#23]
Hi,

at moment I'm using "ldapsearch" from OpenLDAP on Debian for testing.

I'm not sure if this might be a problem with ldapsearch or by some conversion in Your lib:

When the result contains German umlauts the string is a weird combination of numbers and letters...
eg. the query is 'Müller' and the result looks like this:

```
# Julian M\C3\BCller
dn:: Y249SnVsaWFuIE3DvGxsZXIsZGM9SUJMVVBQLGRjPWxvY2Fs
cn:
givenName:: SnVsaWFuIE3DvGxsZXI=
```

but the entry has the correct value:

 ```
           [1] => FreeDSx\Ldap\Entry\Attribute Object
                (
                    [attribute:protected] => givenName
                    [lcAttribute:protected] =>
                    [values:protected] => Array
                        (
                            [0] => Julian Müller
                        )

                    [options:protected] =>
                )
```

I didn't dig deeper in Your code but maybe You could tell me if it's a problem with ldapsearch or with Your lib?

Thanks & cheers,

Stephan

**Comment by ChadSikorra** [comment]
That's definitely a behavior of OpenLDAP's ldapsearch tool. It appears to be outputting base64 encoded data. I'm guessing it might be doing that since it has UTF8 data but doesn't know if your terminal / command prompt can actually display it properly (depending on the locale you have set). So it plays it safe and dumps it in that format. Though that is pretty confusing behavior to be honest.

**Comment by Stephanowicz** [comment]
Ok, thank You!
Hopefully the IP-Phones will handle it better ;)

Cheers, Stephan
