### ISSUE TITLE
Missing schema location in RootDSE, using default schema.

### ISSUE THREAD

**Issue by savedario** [FreeDSx/LDAP#24]
I configured the server to run as a proxy for the 'real' LDAP. The idea, once this is working, is to introduce some logic in between to throttle (slow down) invalid login requests from the clients.

When I connect directly to the LDAP using Apache Directory Studio, I can see all its content as expected.
When I try the connection via the proxy I get the message above, but the connection is open and I can see some of the LDAP contents.
If I edit the connection and use 'Check Network Parameter', 'Check Authentication' and 'Fetch Base DNs', they all work and return the correct value.
The message appears even if I enter the correct Base DN and untick the box "Get Base DN from Root DSE".

This is my ProxyHandler:
```
<?php

namespace DarioLdap;

use FreeDSx\Ldap\Server\RequestContext;
use FreeDSx\Ldap\Operation\Request\SearchRequest;
use FreeDSx\Ldap\Entry\Entries;
use FreeDSx\Ldap\Search\Filters;
use FreeDSx\Ldap\Server\RequestHandler\ProxyRequestHandler;

class LdapProxyHandler extends ProxyRequestHandler
{
    public function __construct()
    {
        $this->options = [
            'page_size' => 1000,
            'timeout_connect' => 5, // was 3
            'timeout_read' => 30, // was 10
            'servers' => ['ldap.example.com:636'],
            'port' => 636,
            'base_dn' => 'dc=example,dc=com',
            'use_ssl' => true,
            'ssl_validate_cert' => false,
        ];
    }

    /**
     * Validates the username/password of a simple bind request
     * Passthrough just to verify this is used
     */
    public function bind(string $username, string $password): bool
    {
        return parent::bind($username,$password);
    }

    /**
     * Override the search request. This must send back an entries object.
     * Just forward the request for now
     *
     * @param RequestContext $context
     * @param SearchRequest $search
     * @return Entries
     */
    public function search(RequestContext $context, SearchRequest $search): Entries
    {
          $filter = $search->getFilter();
          $baseDn = $search->getBaseDn();
          $filter = $search->getBaseDn();
        return parent::search($context, $search);
    }
}
```
and the server is created with:
```
$server = new LdapServer([
    'base_dn' => 'dc=example,dc=com',
    'dse_naming_contexts' => 'dc=example,dc=com',
    'ip' => 'localhost',
    'port' => 17390,
    'request_handler' => LdapProxyHandler::class,
]);
$server->run();
```

**Comment by ChadSikorra** [comment]
Hi there @savedario. I believe the issue is because the LDAP server that gets created with this library returns a very limited RootDSE when one is requested. What gets defined in it happens here: 

https://github.com/FreeDSx/LDAP/blob/master/src/FreeDSx/Ldap/Protocol/ServerProtocolHandler/ServerRootDseHandler.php

Looking at RFC 4512, the following attributes need to be present: 
* altServer: alternative servers;
* namingContexts: naming contexts;
* supportedControl: recognized LDAP controls;
* supportedExtension: recognized LDAP extended operations;
* supportedFeatures: recognized LDAP features;
* supportedLDAPVersion: LDAP versions supported; and
* supportedSASLMechanisms

It additionally states:

> The root DSE may also include a 'subschemaSubentry' attribute.  If it
>    does, the attribute refers to the subschema (sub)entry holding the
>    schema controlling the root DSE.  Clients SHOULD NOT assume that this
>    subschema (sub)entry controls other entries held by the server.

The `subschemaSubentry` is what Apache Studio is likely looking for. But based on RFC 4512, it's a mistake for them to assume it will always exist.

That being said, I should add some way to support additional RootDSE attributes, and definitely add the ones that the RFC defines as being required. Another way of going about this is making a separate interface called something like `RootDseAwareInterface` that could be used by server implementations wanting more control over the RootDSE in general. That would allow you to proxy the RootDSE call back to the real LDAP server, then back to the client.

I'll think about this a bit and then add something.

**Comment by ChadSikorra** [comment]
I have added support to just modify / return your own RootDSE. See the following example:

https://github.com/FreeDSx/LDAP/blob/master/docs/Server/General-Usage.md#handling-the-rootdse

Let me know if this works for you. If so I can tag a new release soon.

**Comment by savedario** [comment]
Thanks for your reply.
As I looked at it, I realized there are a lot of differences between the version I installed with composer and this repository.
E.g. freedsx/src/FreeDSx/Ldap/LdapServer.php
has 3 additional use statements at the top in the repository version; but CHANGELOG.md is identical.
I think I need to sort this before doing anything else...

**Comment by ChadSikorra** [comment]
Yeah, there are substantial changes between the current tagged version and the master branch (I completely refactored how protocol handling is done so I could more easily add SASL support). Using composer though you should just require the autoloader (https://getcomposer.org/doc/01-basic-usage.md#autoloading) and let it sort the classes out itself. To test the most recent changes you would add "dev-master" as the version for this library.

**Comment by savedario** [comment]
For now I just replaced the whole ldap folder with the most recent commit.
I did as you suggested and in my LdapProxyHandler added the following:
```
    public function rootDse(RequestContext $context, SearchRequest $request, Entry $rootDse): Entry
    {
        return $rootDse->add('subschemaSubentry', 'cn=Subschema');
    }
```
At least Apache Directory Studio does not complain anymore (which was my main concern).
Thanks for your help.
