### ISSUE TITLE
Supports Simple Paged Results Control 

### ISSUE THREAD

**Issue by joneppie** [FreeDSx/LDAP#31]
The server does not support Simple Paged Results Control. So requests that require it lead to an error

**Comment by ChadSikorra** [comment]
Thanks for opening this, and apologies for not giving some kind of response. This was on my radar to add, but it is no small effort. I finally took the time to add initial support for this. I still need to add docs for how it works. But it was a lot of new code to support server side paging:

https://github.com/FreeDSx/LDAP/commit/ad620053df499d93a4f01fc5e11166a8cb0df544

Guessing you may not need this anymore since this request is quite old. But I plan to have this available in the next tagged release. With the way it works, you will need to implement a new "paging_handler"class  in the server that implements the "PagingHandlerInterface".  It has two methods, `page()` and `remove()`; this libraries server side code handles all the cookie logic and everything else. If a paging handler is not provided, and the client requested it as "critical", then paging requests will now throw an error on the client / server side.

**Comment by ChadSikorra** [comment]
This has been implemented and documented in the new tagged release. If you have any issues with it let me know. Thanks!
