### ISSUE TITLE
Error 16 (No such attribute) leads to empty message in OperationException

### ISSUE THREAD

**Issue by HenkPoley** [FreeDSx/LDAP#38]
Of course LDAP will never tell you _which_ attribute is wrong, by design. But it would at least be nice to get some kind of hint out of \FreeDSx\Ldap\LdapClient::update() (and probably \FreeDSx\Ldap\LdapClient::create(), or elsewhere?).

I might dig into it myself, but currently just diagnosed that this problem exists.

**Comment by ChadSikorra** [comment]
If it is empty it is likely because the LDAP server is not providing a diagnostic message with the error, since the diagnostic message is optional. One solution would be to provide a more formatted exception message that contains a short name of the result code as defined in RFC 4511, 4.1.9:

 https://tools.ietf.org/html/rfc4511#section-4.1.9

So something like `noSuchAttribute` and optionally tack on the diagnostic message if it exists.

**Comment by ChadSikorra** [comment]
This has been fixed with https://github.com/FreeDSx/LDAP/commit/e69240ae2b67c1f589f199b3470eb86f276ba375. If the server does not respond with a message explaining the error, the exception will format a generic error message. Such as:

> The result code 1 was thrown (operationsError). Indicates that the operation is not properly sequenced with relation to other operations (of same or different type).

You can also get the short string error name off the exception if it exists, including the description:

```php
try {
    $ldap->create($entry);
} catch (OperationException $e) {
    echo sprintf(
        'Error adding entry (%s): %s',
        $e->getCodeShort(), 
        $e->getCodeDescription()
    ) . PHP_EOL;
}
```

Since I just tagged a release, it might be a bit before it is in a tagged version.
