### ISSUE TITLE
LDAP server run (pcntl_fork) spawns zombies on the server

### ISSUE THREAD

**Issue by azovsky** [FreeDSx/LDAP#51]
_For FreeDSx/LDAP v.0.5.0 - 0.7.0. 
On Ubuntu 20.04.3 LTS._

If I run a LDAP server like:

```php
$server = new LdapServer($args);
$server->run();
```
then I see that this spawns zombies processes on a server (hundreds of them)!

To fix this need update **run** function in the file `src/FreeDSx/Ldap/Server/ServerRunner/PcntlServerRunner.php` 

from 

```php
public function run(SocketServer $server): void
    {
        $this->server = $server;

        while ($socket = $this->server->accept()) {
            $pid = pcntl_fork();
            if ($pid == -1) {
                throw new RuntimeException('Unable to fork process.');
            } elseif ($pid === 0) {
                $serverProtocolHandler = new ServerProtocolHandler(
                    new ServerQueue($socket),
                    new HandlerFactory($this->options),
                    $this->options
                );
                $serverProtocolHandler->handle();
                $this->server->removeClient($socket);
                exit;
            }
        }
    }
```

to 

```php
public function run(SocketServer $server): void
{
    $this->server = $server;

    while ($socket = $this->server->accept()) {
        $pid = pcntl_fork();
        if ($pid == -1) {
            throw new RuntimeException('Unable to fork process.');
        } elseif ($pid) {
          // Protect against Zombie children.
          pcntl_wait($status);
        }
        else {
          $serverProtocolHandler = new ServerProtocolHandler(
              new ServerQueue($socket),
              new HandlerFactory($this->options),
              $this->options
          );
          $serverProtocolHandler->handle();
          $this->server->removeClient($socket);
          exit;
        }
    }
}

```

Please see original [php.net > function pcntl_fork()](https://www.php.net/manual/en/function.pcntl-fork.php) documentation.

Thanks!

**Comment by ChadSikorra** [comment]
Uh oh...zombies! 🧟  

That does look right to me. I'll take a look into getting a test in with these changes.

**Comment by ChadSikorra** [comment]
So, by waiting for the child like that it effectively limits the server to handling a single client at a time. I think that's why I originally implemented it like I did. I'm not sure the best way to go about this at the moment. I'll have to mess around with the pcntl related functions more.

**Comment by ChadSikorra** [comment]
Apologies for the time it's taking me to look into this. I've had to focus on other things in my spare time out of work lately.

However, I think the issue is that I need to find a way to asynchronously check the status of the PID that is launched and make sure it gets cleaned-up afterwards so as to not end up with zombie processes. With the way I have the code, it would be possible to create a class implementing `ServerRunnerInterface` and launch the processes differently.

For example, a `ServerRunnerInterface` implementation using a library designed to abstract away a process pool or something like that would be good. It could be put in a separate repository to keep the dependencies of this library isolated. This library looks look a good potential solution: https://github.com/spatie/async

I'm busy working on other priorities this weekend, but will hopefully have time to provide a better solution in the near future.

**Comment by ChadSikorra** [comment]
This should be cleaned up with this PR https://github.com/FreeDSx/LDAP/pull/53. This seems important enough to fix that I'll tag a minor version bump for it. Just going to wait a day or two to make sure I don't think of anything else I missed in regards to this.

**Comment by ChadSikorra** [comment]
Good thing I waited, as I thought of more cases I need to handle 😬 This PR also handles if the server process is shutdown by something like SIGHUP / SIGINT / SIGTERM / SIGQUIT: https://github.com/FreeDSx/LDAP/pull/54. In all of those cases the server will now try to stop all child processes, clean them up properly, and end. It will have a max shutdown time of 15 seconds before it tries to force kill child processes.

**Comment by ChadSikorra** [comment]
This has been resolved now by several commits and I published a new release: 

https://github.com/FreeDSx/LDAP/releases/tag/0.8.0

Due to the synchronous nature of the TCP socket queue this library uses, this is the best I will be able to handle shutting down the server process and make the clients end as they should. It will do its best to send a notice of disconnect to the client as the shutdown occurs. But, depending on what the client is doing, we might not be able to give them a notice and might have to force kill some child processes for the server to go down properly.

But I also added the ability to use a logger in the server process that gives more insight into what is actually happening now. If you have any issues feel free to re-open this!

Thanks again for reporting this.
