### ISSUE TITLE
AD: set unicodePwd 

### ISSUE THREAD

**Issue by splitbrain** [FreeDSx/LDAP#70]
I'm having trouble implementing password changing for Active Directory users and am wondering if I am doing something wrong.

According to the specs, [3.1.1.3.1.5.1 unicodePwd specs](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/6e803168-f140-4d23-b2d3-c3a8ab5917d2?redirectedfrom=MSDN) there are two ways to modify a password:

1. a `modify` request with a `delete` operation for the old password and a `add` operation for the new password
2. a `modify` request with a `replace` operation with the new password

The second method requires an administrative user but works fine:

```
$entry->set('unicodePwd', $this->encodePassword($newpass));
$this->ldap->update($entry);
```

However I can't get the first method working:

```
$entry->remove('unicodePwd', $this->encodePassword($oldpass));
$entry->add('unicodePwd', $this->encodePassword($newpass));
$this->ldap->update($entry);
```

This results in 

```
FreeDSx\Ldap\Exception\OperationException: 0000052D: AtrErr: DSID-03190FC9, #1:
	0: 0000052D: DSID-03190FC9, problem 1005 (CONSTRAINT_ATT_TYPE), data 0, Att 9005a (unicodePwd)

vendor/freedsx/ldap/src/FreeDSx/Ldap/Protocol/ClientProtocolHandler/ClientBasicHandler.php:94
vendor/freedsx/ldap/src/FreeDSx/Ldap/Protocol/ClientProtocolHandler.php:162
...
```

So I guess my question is, does a `remove()` and `add()` operation on the entry, result in the `delete` and `add` operation inside a single `modify` call as specified by Microsoft or should I do something different? Are there any pointers how to debug what's going wrong?

**Comment by ChadSikorra** [comment]
That diagnostic code of `0000052D` in that message refers to this error:

https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--1300-1699-

> ERROR_PASSWORD_RESTRICTION
> 
>     1325 (0x52D)
> 
>     Unable to update the password. The value provided for the new password does not meet the length, complexity, or history requirements of the domain.

When you change the password with a `replace` via an administrative account, it ignores the domain password policy requirements. Where as when you change it with the `remove` and `add` method, it enforces password policy requirements on the new password.

**Comment by splitbrain** [comment]
Hmm I thought so too at first, but even setting a ridiculous long password with all kinds of special chars does not change the result. But if you say my code should be correct, I assume something is wrong with my test AD setup.

**Comment by ChadSikorra** [comment]
What does your code look like that is encoding the old / new value? Also, do you know what the domain password policy is set to (I'm guessing some kind of default..)? I'm not sure if there are other circumstances that would cause AD to throw that same diagnostic code for other issues.

**Comment by splitbrain** [comment]
This is my encoding method. It works fine when running method 2 as admin.

```
    protected function encodePassword($password)
    {
        $password = "\"" . $password . "\"";
        $adpassword = mb_convert_encoding($password, "UTF-16LE", "UTF-8");
        return $adpassword;
    }
```

My policy should be the default. Im using this Vagrant setup for testing: https://github.com/splitbrain/vagrant-active-directory

**Comment by ChadSikorra** [comment]
That all looks fine to me. Do you also encrypt the connection (e.g. do a `startTls()`) prior to the operation? I remember that AD will complain otherwise, but cannot remember what diagnostic code it gives in that case.

**Comment by splitbrain** [comment]
I am using SSL with a self-signed certificate. I believe the changing the password would fail for the admin user, too otherwise.

**Comment by ChadSikorra** [comment]
It's been a while since I've messed with AD, but looking at what the default domain password policy would be out of the box, it would be as follows:

* Minimum of 7 characters.
* Minimum password age of 1 day (You can literally only change the password once in a day...unless done administratively via replace, perhaps this is playing a role?).
* Max password age of 42 days (42....of course 😆).
* Password must meet complexity requirements, which are described here: https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements#reference. Those are actually a little confusing.

To narrow the issue down, does AD allow you to change the password on the same user account via the normal password change screen where you input the old and new password (not the AD module that lets you replace the old password via management tools)?

This library itself does not modify the values in anyway, so I suspect this is something to do with the user account and the password attempting to be used / potentially the timeframe in which it is trying to be changed or the complexity requirements not being met.

**Comment by splitbrain** [comment]
Ohh minimum password age... that might be the problem. I will have to check tomorrow. Thanks for your help so far. Much appreciated!

**Comment by splitbrain** [comment]
That was it indeed. Disabling the MinPasswordAge (using `Set-ADDefaultDomainPasswordPolicy example.local -MinPasswordAge 0` in Powershell) was the solution.

Thanks again for your help, despite this not having anything to do with your awesome library.
